In [3]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('/content/train.csv')
df.head()

                                                text  label        src
0  White girls very rarely date Asian men. Even i...      1  cmv_human
1  I am a 23 year old male Indian American male. ...      1  cmv_human
2  Take three people, Persons A, B, and C. They l...      1  cmv_human
3  (A) Work part-time in high school; Then go to ...      1  cmv_human
4  When police introduce a new form of speed prev...      1  cmv_human

In [6]:
len(df)

319071

In [7]:
df['label'].value_counts()

label
0    225753
1     93318
Name: count, dtype: int64